version: '2'
services:
  php:
    image: bscheshir/php:7.0.12-zts-xdebug
    restart: always
    hostname: phphost
    working_dir: /usr/local/etc/php-code
    volumes:
      - ./../php-code:/usr/local/etc/php-code #php-code
      - ~:/home/user
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.39
      PHP_IDE_CONFIG: "serverName=multispider"

