version: '2'
services:
  php:
    image: bscheshir/php:7.0.12-zts
    restart: always
    hostname: phphost
    working_dir: /usr/local/etc/php-code
    volumes:
      - ./../php-code:/usr/local/etc/php-code #php-code
      - ~:/home/user
