version: '2'
services:
  php:
    image: bscheshir/php:7.0.12-zts
    restart: always
    hostname: phphost
    working_dir: /multispider
    volumes:
      - ./..:/multispider #php-code
      - ~:/home/user
